language: java
jdk: oraclejdk8
before_install:
  - echo $TRAVIS_JDK_VERSION
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_REPO_SLUG
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
